// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2ZopttkBn2UrrF8ShV1G31
// Component: 5h6c7k_6xpcUBj
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: 2ZopttkBn2UrrF8ShV1G31/projectcss
import * as sty from "./PlasmicRatings.module.css"; // plasmic-import: 5h6c7k_6xpcUBj/css

import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: NpbWi19-ClOfhS/icon

export type PlasmicRatings__VariantMembers = {
  stars: "zero" | "one" | "two" | "three" | "four" | "five";
};

export type PlasmicRatings__VariantsArgs = {
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
};

type VariantPropType = keyof PlasmicRatings__VariantsArgs;
export const PlasmicRatings__VariantProps = new Array<VariantPropType>("stars");

export type PlasmicRatings__ArgsType = {
  numReviews?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRatings__ArgsType;
export const PlasmicRatings__ArgProps = new Array<ArgPropType>("numReviews");

export type PlasmicRatings__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultRatingsProps {
  numReviews?: React.ReactNode;
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
  className?: string;
}

function PlasmicRatings__RenderFunc(props: {
  variants: PlasmicRatings__VariantsArgs;
  args: PlasmicRatings__ArgsType;
  overrides: PlasmicRatings__OverridesType;
  dataFetches?: PlasmicRatings__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__stars_five]: hasVariant(variants, "stars", "five"),
        [sty.root__stars_four]: hasVariant(variants, "stars", "four"),
        [sty.root__stars_one]: hasVariant(variants, "stars", "one"),
        [sty.root__stars_three]: hasVariant(variants, "stars", "three"),
        [sty.root__stars_two]: hasVariant(variants, "stars", "two"),
        [sty.root__stars_zero]: hasVariant(variants, "stars", "zero")
      })}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox)}
      >
        {(hasVariant(variants, "stars", "zero") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__qwlZ4, {
              [sty.svg__stars_five__qwlZ48RCfc]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_zero__qwlZ4BJbdB]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__vOPx7, {
              [sty.svg__stars_five__vOPx78RCfc]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__vOPx73S9Tj]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__vOPx7VMEwK]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__vOPx7AAkCb]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__vOPx76Dn9O]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__vOPx7BJbdB]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__fhHqY, {
              [sty.svg__stars_five__fhHqY8RCfc]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__fhHqY3S9Tj]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__fhHqYvMEwK]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__fhHqYaAkCb]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__fhHqY6Dn9O]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__fhHqYbJbdB]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__cl0Ch, {
              [sty.svg__stars_five__cl0Ch8RCfc]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__cl0Ch3S9Tj]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__cl0ChvMEwK]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__cl0ChaAkCb]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__cl0Ch6Dn9O]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__cl0ChBJbdB]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__hj3OP, {
              [sty.svg__stars_five__hj3OP8RCfc]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__hj3OP3S9Tj]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__hj3OPvMEwK]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__hj3OPaAkCb]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__hj3OP6Dn9O]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__hj3OPbJbdB]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? true
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__wQFwU, {
              [sty.svg__stars_five__wQFwU8RCfc]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__wQFwU3S9Tj]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__wQFwUvMEwK]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__wQFwUaAkCb]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__wQFwU6Dn9O]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__wQFwUbJbdB]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__suC5Z, {
              [sty.svg__stars_five__suC5Z8RCfc]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__suC5Z3S9Tj]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_three__suC5ZaAkCb]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__suC5Z6Dn9O]: hasVariant(
                variants,
                "stars",
                "two"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__myCAl, {
              [sty.svg__stars_five__myCAl8RCfc]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__myCAl3S9Tj]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_three__myCAlaAkCb]: hasVariant(
                variants,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__l2Ykd, {
              [sty.svg__stars_five__l2Ykd8RCfc]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__l2Ykd3S9Tj]: hasVariant(
                variants,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg___5CeoH, {
              [sty.svg__stars_five___5CeoH8RCfc]: hasVariant(
                variants,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotNumReviews)
      })}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRatings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRatings__VariantsArgs;
    args?: PlasmicRatings__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRatings__Fetches;
  } & Omit<PlasmicRatings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRatings__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
