// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2ZopttkBn2UrrF8ShV1G31
// Component: WhsmvwL0AEqOG
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: iMnF7iUCZC9QR/component
import ProductCarousel from "../../ProductCarousel"; // plasmic-import: FAMy9Jd3wSIBEr/component
import ProductCard from "../../ProductCard"; // plasmic-import: wkeLS_cqPuA-Uh/component
import Ratings from "../../Ratings"; // plasmic-import: 5h6c7k_6xpcUBj/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: U_D0s_be_wPIx/component
import BlogPost from "../../BlogPost"; // plasmic-import: BgbcMKyT0yf__w/component
import Footer from "../../Footer"; // plasmic-import: kwJJVflWd0r-k/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: B4qIDc-q-Iju3Y/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: 2ZopttkBn2UrrF8ShV1G31/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: WhsmvwL0AEqOG/css

import arrivals1YIcy8NHtGb1Dq from "./images/arrivals1.png"; // plasmic-import: yICY8nHTGb_1dq/picture
import arrivals2CfWcNaGoG9X4 from "./images/arrivals2.png"; // plasmic-import: CfWcNA_go_G9X4/picture
import arrivals3GgPj7H8Wm14Fn6 from "./images/arrivals3.png"; // plasmic-import: GgPj7h8wm14FN6/picture
import arrivals4OuG0Gg7Jq2SAav from "./images/arrivals4.png"; // plasmic-import: ouG0gg7jq2sAav/picture
import arrivals5Vy5SeCvxA6L1 from "./images/arrivals5.png"; // plasmic-import: VY5seCvxA6--l1/picture
import arrivals61Wj1EfuNj7OKr from "./images/arrivals6.png"; // plasmic-import: 1wj1EfuNJ7OKr_/picture
import arrivals7AmSOsUvobjeOGf from "./images/arrivals7.png"; // plasmic-import: amSOsUvobjeOGf/picture
import arrivals82WBhQsJewpNdk8 from "./images/arrivals8.png"; // plasmic-import: 2WBhQSJewpNDK8/picture
import f1CR6HGwu1D0YNyw from "./images/f1.jpeg"; // plasmic-import: cR6hGWU1d0yNyw/picture
import f27HYgFrJg0MKut from "./images/f2.jpeg"; // plasmic-import: -7hYGFrJG0MKut/picture
import f3BZnx78Dm2MVMhE from "./images/f3.jpeg"; // plasmic-import: bZnx78DM2mVMhE/picture
import f4AmccISu71Skws from "./images/f4.jpeg"; // plasmic-import: AmccI-Su71skws/picture
import b1JZz2OqIIrcTjx from "./images/b1.jpeg"; // plasmic-import: JZz2OqIIrcTjx_/picture
import b2IWv81Z1Uzhf2Xd from "./images/b2.jpeg"; // plasmic-import: iWV81Z1uzhf2Xd/picture
import b3UllRmAt0N3V9 from "./images/b3.jpeg"; // plasmic-import: ull_rmAT0-N3V9/picture
import adidasZAoq05GIkirK from "./images/adidas.png"; // plasmic-import: z-Aoq05_GIkirK/picture
import hmEO8AVudpbdllEa from "./images/hm.png"; // plasmic-import: eO8AVudpbdllEa/picture
import kappaRwTqh6NqEngUxU from "./images/kappa.png"; // plasmic-import: RwTQH6NqEngUxU/picture
import lacosteCiEv3H9Woix0Cl from "./images/lacoste.png"; // plasmic-import: CiEV3h9Woix0cl/picture
import levisXOwAnrXJgoSDpj from "./images/levis.png"; // plasmic-import: xOWAnrXJgoSDpj/picture

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  productCarousel?: p.Flex<typeof ProductCarousel>;
  featureItem?: p.Flex<typeof FeatureItem>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultHomeProps {
  className?: string;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  dataFetches?: PlasmicHome__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.freeBox__rjqWg)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__xZqvN)}
            >
              <div className={classNames(defaultcss.all, sty.freeBox__pkkS4)}>
                <Header
                  data-plasmic-name={"header"}
                  data-plasmic-override={overrides.header}
                />

                <ProductCarousel
                  data-plasmic-name={"productCarousel"}
                  data-plasmic-override={overrides.productCarousel}
                  className={classNames("__wab_instance", sty.productCarousel)}
                />
              </div>
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.freeBox__tenpJ)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__nAgWy
                )}
              >
                {"New Arrivals"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox___8CNhl)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__m9TA)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__pgl8X)}
                    role={"img"}
                    src={arrivals1YIcy8NHtGb1Dq}
                  />
                }
                onSale={"onSale" as const}
                price={"$65.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__hp6Se)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__a2RLd)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__kcVLk)}
                    role={"img"}
                    src={arrivals2CfWcNaGoG9X4}
                  />
                }
                onSale={"onSale" as const}
                price={"$80.00"}
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      sty.ratings___3JpsC
                    )}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Single Armchair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__lhX6Z)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__fgI4L)}
                    role={"img"}
                    src={arrivals3GgPj7H8Wm14Fn6}
                  />
                }
                price={"$40.00"}
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      sty.ratings___7P9Qi
                    )}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Armchair"}
              />

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___050GJ
                )}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__srClq)}
                    role={"img"}
                    src={arrivals4OuG0Gg7Jq2SAav}
                  />
                }
                onSale={"onSale" as const}
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__molpW)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Stylish Chair"}
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox___9Hh3)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__gqXz)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__k2RSg)}
                    role={"img"}
                    src={arrivals5Vy5SeCvxA6L1}
                  />
                }
                price={"$120.00"}
                title={"Modern Chair"}
              />

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___60Nuk
                )}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__yQryi)}
                    role={"img"}
                    src={arrivals61Wj1EfuNj7OKr}
                  />
                }
                onSale={"onSale" as const}
                price={"$140.00"}
                title={"Mapple Wood Dinning Table"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__enVc)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__a5Ujp)}
                    role={"img"}
                    src={arrivals7AmSOsUvobjeOGf}
                  />
                }
                onSale={"onSale" as const}
                price={"$90.00"}
                title={"Arm Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__n0Zjb)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__i3Gt1)}
                    role={"img"}
                    src={arrivals82WBhQsJewpNdk8}
                  />
                }
                price={"$140.00"}
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___4UbuF
                    )}
                  >
                    {"Wooden Bed"}
                  </div>
                }
              />
            </p.Stack>

            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(defaultcss.all, sty.freeBox__aobPx)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__rfiIu
                )}
              >
                {"Featured Products"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__lv7GQ)}
            >
              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___46AKb
                )}
                price={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__s34Il
                    )}
                  >
                    {"$160.00"}
                  </div>
                }
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__oYs9Q)}
                    numReviews={"(12 Review)"}
                    stars={"two" as const}
                  />
                }
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___4K1S
                    )}
                  >
                    {"Designed Sofa"}
                  </div>
                }
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__hcExV)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___7E5Cn)}
                    role={"img"}
                    src={f27HYgFrJg0MKut}
                  />
                }
                price={"$200.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__fWa1J)}
                    stars={"four" as const}
                  />
                }
                title={"Dining Table"}
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__vD6C)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__mNamr)}
                    role={"img"}
                    src={f3BZnx78Dm2MVMhE}
                  />
                }
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__d1Zl6)}
                    numReviews={"(23 Review)"}
                    stars={"five" as const}
                  />
                }
                title={"Chair and Table"}
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___2BOeh
                )}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__oiwG3)}
                    role={"img"}
                    src={f4AmccISu71Skws}
                  />
                }
                price={"$299.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__dbXWg)}
                    numReviews={"(35 Review)"}
                  />
                }
                title={"Modern Arm Chair"}
                withReviews={"withReviews" as const}
              />
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.freeBox___3TuHn)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___291Wq
                )}
              >
                {"Latest Blog"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__bfZAi)}
            >
              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__dWSuT)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__ocfvH)}
                    role={"img"}
                    src={b1JZz2OqIIrcTjx}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__wUcT2)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___6A0P)}
                    role={"img"}
                    src={b2IWv81Z1Uzhf2Xd}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost___6Uatk)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__m4QoI)}
                    role={"img"}
                    src={b3UllRmAt0N3V9}
                  />
                }
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__fM6Hd)}
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___6Q1)}
                role={"img"}
                src={adidasZAoq05GIkirK}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__dhfmd)}
                role={"img"}
                src={hmEO8AVudpbdllEa}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__xpHqF)}
                role={"img"}
                src={kappaRwTqh6NqEngUxU}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___8YeYr)}
                role={"img"}
                src={lacosteCiEv3H9Woix0Cl}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___4QbgJ)}
                role={"img"}
                src={levisXOwAnrXJgoSDpj}
              />
            </p.Stack>

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "productCarousel", "featureItem", "footer"],
  header: ["header"],
  productCarousel: ["productCarousel"],
  featureItem: ["featureItem"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  productCarousel: typeof ProductCarousel;
  featureItem: typeof FeatureItem;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHome__Fetches;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    productCarousel: makeNodeComponent("productCarousel"),
    featureItem: makeNodeComponent("featureItem"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
